# Generated by Django 6.0.3 on 2026-04-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GeneralApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("resume", models.FileField(upload_to="resumes/")),
                ("cover_letter", models.TextField()),
                (
                    "skills",
                    models.TextField(help_text="Comma-separated list of skills"),
                ),
                ("experience_years", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("uyo", "Uyo"),
                            ("abuja", "Abuja"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-Time"),
                            ("part-time", "Part-Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
