# Generated by Django 6.0.3 on 2026-05-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceinquiry",
            name="service",
        ),
        migrations.DeleteModel(
            name="Testimonial",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.DeleteModel(
            name="ServiceInquiry",
        ),
    ]
